### ISSUE TITLE
Public Bonds

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquity-dollar#153]
Can we capitalize on our bond system somehow to the community?

Inspiration:
https://twitter.com/PoseysThumbs/status/1436206056191901699
https://forum.alchemix.fi/public/d/210-aip-21-alcx-bond-program

**Comment by hpiyankov** [comment]
Here is what they are saying in a nutshell:

1. We give free tokens in exchange for liquidity - this is bad since it creates inflation and in exchange, we get only temp liquidity
2. Instead of giving you tokens for temporary liquidity.... we want to give you tokens for permanent liquidity - e.g. we will purchase your liquidity from you in exchange for tokens.

Can this work? - Sure it all depends on the price. The problem is that the only value under which this makes sense is if the value of the tokens obtained is slightly higher than the value of LP position. 
The problem with this is then this becomes pure arbitrage :

1. Create LP position
2. Sell it at a premium
3. Sell half of the tokens obtained
4. Create a new, slightly higher LP position (with the proceeds)
5. Repeat

The way that this could work is if there is a token that is ONLY obtainable by selling your LP position, but even then it does not make a lot of sense to me.  In a nutshell, all of this sounds like an austerity measure masked as a feature.
