### ISSUE TITLE
Wrong route of libraries

### ISSUE THREAD

**Issue by hackingsub** [ubiquity/ubiquity-dollar#157]
Use:

"../node_modules/@openzeppelin/contracts/math/SafeMath.sol"

Instead of: 

"@openzeppelin/contracts/math/SafeMath.sol";

**Comment by kamiebisu** [comment]
Unfortunately, changing that in the contracts broke Hardhat's compilation. It doesn't compile any of the contracts with that import statement and raises a `File outside of allowed directories` error. I tried passing the `allow-paths` configuration to Hardhat's solc settings, but it also didn't work.

Would you mind making those changes locally so that you can run the analyzers?
